version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Pre-build phase"
      - echo "S3_BUCKET_NAME is $S3_BUCKET_NAME"
      - echo "S3_BUCKET_REGION is $S3_BUCKET_REGION"
      - python manage.py collectstatic --noinput --verbosity 2
      - aws s3 sync static/ s3://$S3_BUCKET_NAME/static/ --region $S3_BUCKET_REGION
      - echo "Invalidating CloudFront cache"
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
  build:
    commands:
      - echo "Build phase"
      - python manage.py migrate
#      - python manage.py test
  post_build:
    commands:
      - echo "Post-build phase"
      - echo "Build completed on `date`"
artifacts:
  files:
    - '**/*'