version: '3.8'

services:
  web:
    build: .
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "80:8000"
# For local development, you can use the following configuration:
#    env_file:
#      - .env
    environment:
      - S3_BUCKET_NAME
      - S3_BUCKET_REGION
      - DJANGO_SECRET_KEY
      - REDIS_URL=redis://redis:6379/1
      - CACHE_TIMEOUT=31536000
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"